language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
# command to install dependencies
before_install:
  - sudo apt-get install root-system
  - root --version
install:
  - pip install .
# command to run tests
script:
  - pytest -k "not root and not fluka"
